### PR TITLE
Fixed issues with GeoTiff reading and projection

### LINKED ISSUE #1341: LatLon tiles CRS read problem
Probably we have a problem with tile tags reading (was noticed only with `LatLon` (checked it on `merc`, `utm` and `modis sinusoidal`)).

What we have: 
A `LatLon` tile:
```
$ gdalinfo -proj4 all-ones.tif 
Driver: GTiff/GeoTIFF
Files: all-ones.tif
Size is 512, 512
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
PROJ.4 string is:
'+proj=longlat +datum=WGS84 +no_defs '
Origin = (141.706666666666706,-17.520000000000010)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 141.7066667, -17.5200000) (141d42'24.00"E, 17d31'12.00"S)
Lower Left  ( 141.7066667, -17.9466667) (141d42'24.00"E, 17d56'48.00"S)
Upper Right ( 142.1333333, -17.5200000) (142d 8' 0.00"E, 17d31'12.00"S)
Lower Right ( 142.1333333, -17.9466667) (142d 8' 0.00"E, 17d56'48.00"S)
Center      ( 141.9200000, -17.7333333) (141d55'12.00"E, 17d44' 0.00"S)
Band 1 Block=512x4 Type=Float32, ColorInterp=Gray
  NoData Value=-9999
```
```
$ listgeo all-ones.tif
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         141.706666666667  -17.52            0                
      ModelPixelScaleTag (1,3):
         0.000833333333333325 0.000833333333333332 0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeGeographic
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GeographicTypeGeoKey (Short,1): GCS_WGS_84
      GeogCitationGeoKey (Ascii,7): "WGS 84"
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      GeogSemiMajorAxisGeoKey (Double,1): 6378137          
      GeogInvFlatteningGeoKey (Double,1): 298.257223563    
      End_Of_Keys.
   End_Of_Geotiff.

GCS: 4326/WGS 84
Datum: 6326/World Geodetic System 1984
Ellipsoid: 7030/WGS 84 (6378137.00,6356752.31)
Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
Projection Linear Units: User-Defined (1.000000m)

Corner Coordinates:
Upper Left    (141d42'24.00"E, 17d31'12.00"S)
Lower Left    (141d42'24.00"E, 17d56'48.00"S)
Upper Right   (142d 8' 0.00"E, 17d31'12.00"S)
Lower Right   (142d 8' 0.00"E, 17d56'48.00"S)
Center        (141d55'12.00"E, 17d44' 0.00"S)
```

When we read this tile metadata (using `RasterMetaData.fromRdd(rdd, layoutScheme)`) the proj4 string of the projection in metadata is:

```
+proj=latlong +datum=WGS84 +to_meter=1.0 
```

and we expect to have 

```
+proj=latlong +datum=WGS84 +no_defs
``` 

The problem is caused by a wrong `GTModelTypeGeoKey` read from tiff tags (but think it is not the root of the problem).

Our parser sets `LatLon` projection but with `ModelTypeCode (GTModelTypeGeoKey)` set to 2 (Geographic latitude-longitude System): http://www.remotesensing.org/geotiff/spec/geotiff6.html

https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/GeoKeyReader.scala#L47-L49

### PR DESCRIPTION
**Pull request by lossyrob**
- GeoTiff tag reader was not reading the RowsPerStrip tag correctly when that tag was written as an Int instead of a Short
- GeoTiff reader was not reading Coordinate Systems with ModelType = Geographic correctly
- Projection used reference equality to compare units to Units.DEGREES, which doesn't work with serialization. Changed to structural equality.
- Added support for writing and reading AREA_OR_PIXEL and TIFFTAG_DATETIME metadata tags
- Fixed writing of Geographic CRSes to GeoTiff.

Fixes #1341

### CODE REVIEW

File: proj4/src/main/java/org/osgeo/proj4j/proj/Projection.java [hunk 1]
```diff
@@ -253,7 +253,7 @@ public ProjCoordinate projectRadians( ProjCoordinate src, ProjCoordinate dst ) {
      */
     private ProjCoordinate projectRadians(double x, double y, ProjCoordinate dst ) {
         project(x, y, dst);
-        if (unit == Units.DEGREES) {
+        if (unit != null && unit.equals(Units.DEGREES)) {
```
Comment (lossyrob) [inline proj4/src/main/java/org/osgeo/proj4j/proj/Projection.java]: @dwins just as an FYI, there were 2 other places in this file (this is one) where there were serialization issues w/ reference equaliy.
