### PR TITLE
Cassandra Unit Tests GO

### LINKED ISSUE #1097: Cassandra server handling in tests
**GSoc2015 GeoTrellis Cassandra tracker for shared scratch documentation**

If cassandra server is not running, geotrellis-spark (feature-cassandra as of now) tests will fail.

**Update 26.05.2015**
This is not directly true actually. In fact, the geotrellis-spark cassandra tests use the `useCassandraConfig` embedded service from the datastax spark-cassandra-connector, which actually starts a cassandra instance in the JVM, just like we want. However, it has a timeout of 10 seconds and if the cassandra daemon isn't responsive than the test will fail. Also the tests **cannot** be run in parallel! [Spark-Cassandra-Connector EmbeddedCassandra.scala](https://github.com/datastax/spark-cassandra-connector/blob/v1.2.1/spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/EmbeddedCassandra.scala)

---

Workarounds/solutions, either define switch to skip Cassandra tests if no cassandra instance is available (keyspace config?) or ideally launch embedded instance, similar to accumulo tests

Some links I'll follow up on, where projects use Embedded Cassandra testing environments:

- found in DataStax Spark Cassandra Connector
  - https://github.com/datastax/spark-cassandra-connector/commit/550517a92ae1ff0475d52a0b5dd5bb6dac0f8803
- jsevellec/cassandra-unit
  - https://github.com/jsevellec/cassandra-unit/wiki/How-to-use-it-in-your-code
- Netflix/astyanax (http://techblog.netflix.com/2012/01/announcing-astyanax.html), embedded cassandra incl conf.yaml, seems they actually raise an embedded instance incl config
  - https://github.com/Netflix/astyanax/tree/master/astyanax-cassandra/src/main/resources
  - https://github.com/Netflix/astyanax/blob/master/astyanax-cassandra/src/main/java/com/netflix/astyanax/test/EmbeddedCassandra.java
- also found CassandraDaemon / EmbeddedServer) in cassandra git
  - https://git1-us-west.apache.org/repos/asf?p=cassandra.git;a=blob;f=test/unit/org/apache/cassandra/EmbeddedServer.java;h=25754ea4becf0de531232fc69d197ec3b37ae96d;hb=HEAD

### PR DESCRIPTION
**Pull request by allixender**
Fixes #1097 

- updated spark cassandra connector and cassandra java driver versions to latest stable in Version.scala
- fixed cassandra config yaml (another-cassandra.yaml) for embedded Cassandra instance
- fixed SparkContext needing cassandra connection properties at creation in OnlyIfCanRunSpark.scala
- fixed "LayerNotFoundError expected but RuntimeError found", wasn't thrown in CassandraRasterCatalogSpec.scala tests, found Sys.error instead of throws Exception in CassandraAttributeStore.scala, replaced with LayerNotForundError from package.scala

ALL CASSANDRA UNIT TESTS COMPLETE SUCCESSFULLY

**JAVA INFO**
Seems that with (Open)JDK 7_80 CassandraRasterCatalogSpec.scala test fails occasionally with OutOfMemory / PermGenSpace, (MaxPermSize=384m come from somewhere), but with JDK 8 PermGenSpace has been removed and will complete.

Be aware that if the tests abort because of such an exception, the cassandra instance will not be properly shut down and block the ports!

### CODE REVIEW

File: spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala [hunk 1]
```diff
@@ -60,11 +60,14 @@ class CassandraAttributeStore(val attributeTable: String)(implicit session: Cass
...
+    // FIXME is that right to better throw those exception?
     val size = values.getAvailableWithoutFetching
     if(size == 0) {
-      sys.error(s"Attribute $attributeName not found for layer $layerId")
+      // sys.error(s"Attribute $attributeName not found for layer $layerId")
+      throw new LayerNotFoundError(layerId)
     } else if (size > 1) {
-      sys.error(s"Multiple attributes found for $attributeName for layer $layerId")
+      // sys.error(s"Multiple attributes found for $attributeName for layer $layerId")
+      throw new MultipleMatchError(layerId)
```
Comment (lossyrob) [inline spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala]: Sure, that seems good. I would want the messages to be the same, having a "MultipleMatchError" type is informative but the message is more informative.

File: spark/src/test/scala/geotrellis/spark/OnlyIfCanRunSpark.scala [hunk 2]
```diff
@@ -16,18 +16,31 @@
...
+    useCassandraConfig(Seq("another-cassandra.yaml"))
+    val host = getHost().getHostAddress
+    val rpcPort : Int = getRpcPort()
+    val nativePort : Int = getNativePort()
+
+    sparkConf.set("spark.cassandra.connection.host", host)
+      .set("spark.cassandra.connection.rpc.port", rpcPort.toString)
+      .set("spark.cassandra.connection.native.port", nativePort.toString)
+
+    // val sparkContext = SparkUtils.createLocalSparkContext("local[8]", "Test Context", new SparkConf())
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/OnlyIfCanRunSpark.scala]: remove comments

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeStoreSpec.scala [hunk 3]
```diff
@@ -16,21 +16,31 @@ import spray.json.DefaultJsonProtocol._
...
+      // useCassandraConfig(Seq("cassandra-default.yaml.template"))
+      useCassandraConfig(Seq("another-cassandra.yaml"))
+      val host = getHost().getHostAddress
+      val rpcPort : Int = getRpcPort()
+      val nativePort : Int = getNativePort()
+
+      val testValue = sc.getConf.get("spark.cassandra.connection.host")
+      println(s"get sparkConf in Cassandra Attribute Catalog ${testValue} host ")
+
+      // EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeStoreSpec.scala]: remove commented out code

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeStoreSpec.scala [hunk 4]
```diff
@@ -16,21 +16,31 @@ import spray.json.DefaultJsonProtocol._
...
+    with OnlyIfCanRunSpark
+    with Logging
     with SharedEmbeddedCassandra {
 
   describe("Cassandra Attribute Catalog") {
     ifCanRunSpark {
 
-      useCassandraConfig("cassandra-default.yaml.template")
-      EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
+      // useCassandraConfig(Seq("cassandra-default.yaml.template"))
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeStoreSpec.scala]: rmv

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala [hunk 5]
```diff
@@ -38,27 +38,42 @@ class CassandraRasterCatalogSpec extends FunSpec
...
     ifCanRunSpark { 
 
-      useCassandraConfig("cassandra-default.yaml.template")
-      EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
+      // useCassandraConfig(Seq("cassandra-default.yaml.template"))
+      useCassandraConfig(Seq("another-cassandra.yaml"))
+      val host = getHost().getHostAddress
+      val rpcPort : Int = getRpcPort()
+      val nativePort : Int = getNativePort()
+      // EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: rmv

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala [hunk 6]
```diff
@@ -67,7 +82,8 @@ class CassandraRasterCatalogSpec extends FunSpec
             val tile = getTile(key)
             (tile.cols, tile.rows) should be ((512, 512))
           }
-          
+          // FIXME: Expected exception geotrellis.spark.io.package$LayerNotFoundError to be thrown,
+          // but java.lang.RuntimeException was thrown. (CassandraRasterCatalogSpec.scala:87
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: what's going on with this FIXME? (Also we generally use `TODO` instead of `FIXME`)

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala [hunk 7]
```diff
@@ -95,9 +111,15 @@ class CassandraRasterCatalogSpec extends FunSpec
   }
 
   describe("Cassandra Raster Catalog with SpaceTime Rasters") {
-    ifCanRunSpark { 
-      useCassandraConfig("cassandra-default.yaml.template")
-      EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
+    ifCanRunSpark {
+      // useCassandraConfig(Seq("cassandra-default.yaml.template"))
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: rmv

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala [hunk 8]
```diff
@@ -95,9 +111,15 @@ class CassandraRasterCatalogSpec extends FunSpec
...
+      useCassandraConfig(Seq("another-cassandra.yaml"))
+      val host = getHost().getHostAddress
+      val rpcPort : Int = getRpcPort()
+      val nativePort : Int = getNativePort()
+      // EmbeddedCassandra.withSession(cassandraHost.getHostAddress(), "test") { implicit session =>
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: rmv

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala [hunk 9]
```diff
@@ -122,7 +144,8 @@ class CassandraRasterCatalogSpec extends FunSpec
           val actual = CoordinateSpaceTime.collect.toMap.apply(key)
           tilesEqual(tile, actual)
         }
-        
+        // FIXME: Expected exception geotrellis.spark.io.package$LayerNotFoundError to be thrown,
+        // but java.lang.RuntimeException was thrown. (CassandraRasterCatalogSpec.scala:148)
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: ?

File: spark/src/test/scala/geotrellis/spark/io/cassandra/EmbeddedCassandraConnector.scala [hunk 10]
```diff
@@ -1,24 +1,52 @@
...
   // Recreate the keyspace with each session, and prevent premature closure of session.
-  def withSession(host: String, keySpace: String)(f: CassandraSession => Unit)(implicit sc: SparkContext): Unit = {
+  def withSession(host: String, rpcPort: Int, nativePort: Int, keySpace: String)(f: CassandraSession => Unit)(implicit sc: SparkContext): Unit = {
     val sparkConf = sc.getConf
-    val hadoopConf = sc.hadoopConfiguration
     sparkConf.set("spark.cassandra.connection.host", host)
+      .set("spark.cassandra.connection.rpc.port", rpcPort.toString)
+      .set("spark.cassandra.connection.native.port", nativePort.toString)
+    // https://github.com/datastax/spark-cassandra-connector/blob/master/doc/1_connecting.md
+    // val sc = new SparkContext("spark://127.0.0.1", "test", sparkConf)
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/EmbeddedCassandraConnector.scala]: rmv comments

File: spark/src/test/scala/geotrellis/spark/io/cassandra/EmbeddedCassandraConnector.scala [hunk 11]
```diff
@@ -1,24 +1,52 @@
...
+//
+//object EmbeddedCassandraSession {
+//  implicit def cassandraSessionToDataStaxSession(session: EmbeddedCassandraSession): Session =
+//    session.session
+//}
+//
+//class EmbeddedCassandraSession( connector: CassandraConnector,  val keySpace: String ) {
+//  private val session: Session = connector.openSession()
+//  def close() = session.close
+//}
```
Comment (lossyrob) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/EmbeddedCassandraConnector.scala]: rmv commented ouf code

File: spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala (hunk 9 above)
Comment (allixender) [inline spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala]: These fixme comments were where the tests failed because the expected exception wasn't originally thrown in the implementing catalog class.

I'll remove all comments.

**Comment by lossyrob** [comment]
:+1:
