### PR TITLE
Fixed a bug in vectorization.

### LINKED ISSUE #1350: Creating PolygonFeature List using tile ToVector fails
Using a single Tile, not RDD, and I get Message: "com.vividsolutions.jts.geom.MultiPolygon cannot be cast to com.vividsolutions.jts.geom.Polygon". 

```console
Stack Trace:

Message: com.vividsolutions.jts.geom.MultiPolygon cannot be cast to com.vividsolutions.jts.geom.Polygon
 Trace: geotrellis.vector.Polygon$.apply(Polygon.scala:68)
geotrellis.raster.op.global.ToVector$.apply(ToVector.scala:120)
geotrellis.raster.op.global.GlobalMethods$class.toVector(GlobalMethods.scala:23)
geotrellis.raster.op.global.package$GlobalMethodExtensions.toVector(package.scala:22)
geotrellis.raster.op.global.GlobalMethods$class.toVector(GlobalMethods.scala:17)
geotrellis.raster.op.global.package$GlobalMethodExtensions.toVector(package.scala:22)
tutorial.GeoTrellisService$$anonfun$ingestRoute$3$$anonfun$apply$19.apply(GeoTrellisService.scala:851)
tutorial.GeoTrellisService$$anonfun$ingestRoute$3$$anonfun$apply$19.apply(GeoTrellisService.scala:685)
spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:49)
spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:48)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
spray.routing.RequestContext.reject(RequestContext.scala:202)
spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
spray.routing.RequestContext.reject(RequestContext.scala:202)
```

### LINKED ISSUE #1361: Vectorize Issue
In some circumstances when vectorizing an Array Tile the Polygon class will throw an error that it cannot cast type Multipolygon to Polygon around line 70.  The line that is failing is **p.buffer(0).asInstanceOf[jts.Polygon]**

I grabbed the source modified it to this instead: 
**val buff = p.buffer(0)
      if(buff.getGeometryType() == "MultiPolygon"){
        val t = "test"
        buff.asInstanceOf[jts.MultiPolygon].head
      }
      else{
        buff.asInstanceOf[jts.Polygon] 
      }**

That fixed that error but left incomplete polygons I added a couple methods in my copy to always vectorize to multipolygons, leaving the original so it wouldn't break anything .  This added code to the Multipolygon and Vectorize and VectorizeMethods.

### PR DESCRIPTION
**Pull request by lossyrob**
There was a bug in situations where we were generating polygons with holes, of various values; if the linear rings that were generated for the holes of a polygon intersected, it would produce incorrect geometries. This fix unions all holes so that we are assigning unique non-intersecting linear rings to polygon holes.

/cc @owcm @kagoentzel 

Fixes #1350
Fixes #1361

### CODE REVIEW

File: raster/src/main/scala/geotrellis/raster/vectorize/Vectorize.scala [hunk 1]
```diff
@@ -116,8 +115,21 @@ object Vectorize {
...
+                  case None => Set[Line]()
+                }
+              } else {
+                h.toSet
+              }
+            }
+
             polygons += PolygonFeature(
-              Polygon(Line(shell), callback.linearRings.map(Line.apply).toSet),
+              Polygon(Line(shell), holes),
```
Comment (lossyrob) [inline raster/src/main/scala/geotrellis/raster/vectorize/Vectorize.scala]: This is really the fix, there's also some formatting and cleanup in this PR.

Comment (kagoentzel) [inline raster/src/main/scala/geotrellis/raster/vectorize/Vectorize.scala]: Hey Rob,

Those changes work great. 

Thanks,

Keith

Keith Goentzel | Senior Software Engineer | Swova 
m.  913.800.1764 | e. keith@swova.com <mailto:keith@swova.com> | w. www.swova.com <http://www.swova.com/>

**Comment by echeipesh** [comment]
+1
